import sys
import os
import zlib
import struct

def paeth_predictor(a, b, c):
    p = a + b - c
    pa = abs(p - a)
    pb = abs(p - b)
    pc = abs(p - c)
    if pa <= pb and pa <= pc: return a
    elif pb <= pc: return b
    return c

def read_png_rgba_64x64(png_path):
    with open(png_path, "rb") as f:
        if f.read(8) != b"\x89PNG\r\n\x1a\n":
            print("Error: Not a valid PNG file.")
            sys.exit(1)
            
        idat_data = b""
        has_alpha = False
        while True:
            chunk_header = f.read(8)
            if not chunk_header or len(chunk_header) < 8:
                break
            length, chunk_type = struct.unpack(">I4s", chunk_header)
            data = f.read(length)
            f.read(4) # CRC
            
            if chunk_type == b"IHDR":
                w, h, depth, color_type = struct.unpack(">IIBB", data[:10])
                if w != 64 or h != 64:
                    print(f"Error: Image size must be exactly 64x64. Found {w}x{h}")
                    sys.exit(1)
                if color_type == 6:
                    has_alpha = True
                elif color_type != 2:
                    print("Error: Please save PNG as RGB or RGBA Truecolor.")
                    sys.exit(1)
            elif chunk_type == b"IDAT":
                idat_data += data
            elif chunk_type == b"IEND":
                break
                
        decompressed = zlib.decompress(idat_data)
        channels = 4 if has_alpha else 3
        stride = 1 + 64 * channels
        rgba_pixels = []
        
        # Flawless PNG Filter Reconstruction Matrix (None, Sub, Up, Average, Paeth)
        prev_row = [0] * (64 * channels)
        for y in range(64):
            row_data = decompressed[y * stride : (y + 1) * stride]
            filter_type = row_data[0]
            current_raw = list(row_data[1:])
            current_row = [0] * (64 * channels)
            
            for i in range(64 * channels):
                raw_val = current_raw[i]
                
                # Fetch relative pixel pointers for neighbor reconstruction
                left = current_row[i - channels] if i >= channels else 0
                up = prev_row[i]
                upper_left = prev_row[i - channels] if i >= channels else 0
                
                if filter_type == 0:   # 0: None
                    current_row[i] = raw_val
                elif filter_type == 1: # 1: Sub
                    current_row[i] = (raw_val + left) & 0xFF
                elif filter_type == 2: # 2: Up
                    current_row[i] = (raw_val + up) & 0xFF
                elif filter_type == 3: # 3: Average
                    current_row[i] = (raw_val + ((left + up) // 2)) & 0xFF
                elif filter_type == 4: # 4: Paeth
                    p_pred = paeth_predictor(left, up, upper_left)
                    current_row[i] = (raw_val + p_pred) & 0xFF
                else:
                    current_row[i] = raw_val
                    
            prev_row = current_row
            for x in range(64):
                idx = x * channels
                r = current_row[idx]
                g = current_row[idx+1]
                b = current_row[idx+2]
                a = current_row[idx+3] if has_alpha else 255
                rgba_pixels.append((r, g, b, a))
                
        return rgba_pixels

def main():
    input_dir = "."
    output_dir = "."
    if len(sys.argv) > 1:
        input_dir = sys.argv[1]
    if len(sys.argv) > 2:
        output_dir = sys.argv[2]
        
    png_path = os.path.join(input_dir, "Lakka.png")
    header_path = os.path.join(output_dir, "lakka_logo_res.h")
    
    if not os.path.exists(png_path):
        print(f"Error: {png_path} not found.")
        sys.exit(1)
        
    print(f"Asset Pipeline: Parsing target image from {png_path}")
    pixels = read_png_rgba_64x64(png_path)
    
    print(f"Asset Pipeline: Translating original colors and writing array to {header_path}")
    with open(header_path, "w") as f:
        f.write("/* Automatically generated by flaw-free pure python png_to_header.py - DO NOT EDIT */\n")
        f.write("#ifndef LAKKA_LOGO_RES_H\n")
        f.write("#define LAKKA_LOGO_RES_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("static const uint16_t lakka_logo_64x64[64 * 64] = {\n")
        
        for y in range(64):
            f.write("    ")
            for x in range(64):
                r, g, b, a = pixels[y * 64 + x]
                
                if a < 128:
                    color_565 = 0x0000
                else:
                    r_565 = ((r >> 3) & 0x1F) << 11
                    g_565 = ((g >> 2) & 0x3F) << 5
                    b_565 = (b >> 3) & 0x1F
                    color_565 = r_565 | g_565 | b_565
                    
                    if color_565 == 0x0000:
                        color_565 = 0x0821 
                        
                f.write(f"0x{color_565:04X}, ")
            f.write("\n")
            
        f.write("};\n\n")
        f.write("#endif /* LAKKA_LOGO_RES_H */\n")

if __name__ == "__main__":
    main()
